// <auto-generated />
namespace i2MFCS.WMS.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CommandERP : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CommandERP));
        
        string IMigrationMetadata.Id
        {
            get { return "201803181215398_CommandERP"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
