// <auto-generated />
namespace i2MFCS.WMS.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Command_Order_ID_RequiredOff : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Command_Order_ID_RequiredOff));
        
        string IMigrationMetadata.Id
        {
            get { return "201802262202063_Command_Order_ID_RequiredOff"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
