//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ERPInterface.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ERPInterface.xsd", IsNullable=false)]
public partial class ERPCommand {
    
    private SKUIDUpdateType[] sKUIDUpdateField;
    
    private TUCreateType[] tUCreateField;
    
    private TUDeleteType[] tUDeleteField;
    
    private TUDeleteType[] tUChangeField;
    
    private TUCreateSKUType[] tUCreateSKUField;
    
    private TUCreateSKUType[] tUDeleteSKUField;
    
    private MoveType[] moveField;
    
    private CancelType[] cancelField;
    
    private StatusType[] statusField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SKUIDUpdate")]
    public SKUIDUpdateType[] SKUIDUpdate {
        get {
            return this.sKUIDUpdateField;
        }
        set {
            this.sKUIDUpdateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TUCreate")]
    public TUCreateType[] TUCreate {
        get {
            return this.tUCreateField;
        }
        set {
            this.tUCreateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TUDelete")]
    public TUDeleteType[] TUDelete {
        get {
            return this.tUDeleteField;
        }
        set {
            this.tUDeleteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TUChange")]
    public TUDeleteType[] TUChange {
        get {
            return this.tUChangeField;
        }
        set {
            this.tUChangeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TUCreateSKU")]
    public TUCreateSKUType[] TUCreateSKU {
        get {
            return this.tUCreateSKUField;
        }
        set {
            this.tUCreateSKUField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TUDeleteSKU")]
    public TUCreateSKUType[] TUDeleteSKU {
        get {
            return this.tUDeleteSKUField;
        }
        set {
            this.tUDeleteSKUField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Move")]
    public MoveType[] Move {
        get {
            return this.moveField;
        }
        set {
            this.moveField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cancel")]
    public CancelType[] Cancel {
        get {
            return this.cancelField;
        }
        set {
            this.cancelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Status")]
    public StatusType[] Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/ERPInterface.xsd")]
public partial class SKUIDUpdateType {
    
    private int eRPIDField;
    
    private SKUIDType sKUIDField;
    
    /// <remarks/>
    public int ERPID {
        get {
            return this.eRPIDField;
        }
        set {
            this.eRPIDField = value;
        }
    }
    
    /// <remarks/>
    public SKUIDType SKUID {
        get {
            return this.sKUIDField;
        }
        set {
            this.sKUIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/ERPInterface.xsd")]
public partial class SKUIDType {
    
    private string idField;
    
    private string descriptionField;
    
    private double quantityField;
    
    private string unitField;
    
    private double weightField;
    
    private int timeToleranceField;
    
    /// <remarks/>
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public double Quantity {
        get {
            return this.quantityField;
        }
        set {
            this.quantityField = value;
        }
    }
    
    /// <remarks/>
    public string Unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    public double Weight {
        get {
            return this.weightField;
        }
        set {
            this.weightField = value;
        }
    }
    
    /// <remarks/>
    public int TimeTolerance {
        get {
            return this.timeToleranceField;
        }
        set {
            this.timeToleranceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/ERPInterface.xsd")]
public partial class StatusType {
    
    private int eRPIDField;
    
    private int[] commandIDField;
    
    /// <remarks/>
    public int ERPID {
        get {
            return this.eRPIDField;
        }
        set {
            this.eRPIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CommandID")]
    public int[] CommandID {
        get {
            return this.commandIDField;
        }
        set {
            this.commandIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/ERPInterface.xsd")]
public partial class CancelType {
    
    private int eRPIDField;
    
    private int[] commandIDField;
    
    /// <remarks/>
    public int ERPID {
        get {
            return this.eRPIDField;
        }
        set {
            this.eRPIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CommandID")]
    public int[] CommandID {
        get {
            return this.commandIDField;
        }
        set {
            this.commandIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/ERPInterface.xsd")]
public partial class SKUCall {
    
    private string sKUIDField;
    
    private double quantityField;
    
    private string batchField;
    
    /// <remarks/>
    public string SKUID {
        get {
            return this.sKUIDField;
        }
        set {
            this.sKUIDField = value;
        }
    }
    
    /// <remarks/>
    public double Quantity {
        get {
            return this.quantityField;
        }
        set {
            this.quantityField = value;
        }
    }
    
    /// <remarks/>
    public string Batch {
        get {
            return this.batchField;
        }
        set {
            this.batchField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/ERPInterface.xsd")]
public partial class SubOrderType {
    
    private int subOrderIDField;
    
    private string nameField;
    
    private SKUCall[] sKUField;
    
    /// <remarks/>
    public int SubOrderID {
        get {
            return this.subOrderIDField;
        }
        set {
            this.subOrderIDField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SKU")]
    public SKUCall[] SKU {
        get {
            return this.sKUField;
        }
        set {
            this.sKUField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/ERPInterface.xsd")]
public partial class OrderType {
    
    private int orderIDField;
    
    private System.DateTime releaseTimeField;
    
    private string locationField;
    
    private SubOrderType[] subOrderField;
    
    /// <remarks/>
    public int OrderID {
        get {
            return this.orderIDField;
        }
        set {
            this.orderIDField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime ReleaseTime {
        get {
            return this.releaseTimeField;
        }
        set {
            this.releaseTimeField = value;
        }
    }
    
    /// <remarks/>
    public string Location {
        get {
            return this.locationField;
        }
        set {
            this.locationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SubOrder")]
    public SubOrderType[] SubOrder {
        get {
            return this.subOrderField;
        }
        set {
            this.subOrderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/ERPInterface.xsd")]
public partial class MoveType {
    
    private int eRPIDField;
    
    private OrderType[] orderField;
    
    /// <remarks/>
    public int ERPID {
        get {
            return this.eRPIDField;
        }
        set {
            this.eRPIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Order")]
    public OrderType[] Order {
        get {
            return this.orderField;
        }
        set {
            this.orderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/ERPInterface.xsd")]
public partial class SKUType {
    
    private string sKUIDField;
    
    private double quantityField;
    
    private string batchField;
    
    private System.DateTime prodDateField;
    
    private System.DateTime expDateField;
    
    /// <remarks/>
    public string SKUID {
        get {
            return this.sKUIDField;
        }
        set {
            this.sKUIDField = value;
        }
    }
    
    /// <remarks/>
    public double Quantity {
        get {
            return this.quantityField;
        }
        set {
            this.quantityField = value;
        }
    }
    
    /// <remarks/>
    public string Batch {
        get {
            return this.batchField;
        }
        set {
            this.batchField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime ProdDate {
        get {
            return this.prodDateField;
        }
        set {
            this.prodDateField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime ExpDate {
        get {
            return this.expDateField;
        }
        set {
            this.expDateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/ERPInterface.xsd")]
public partial class TUCreateSKUTypeTU {
    
    private int tUIDField;
    
    private SKUType[] sKUField;
    
    /// <remarks/>
    public int TUID {
        get {
            return this.tUIDField;
        }
        set {
            this.tUIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SKU")]
    public SKUType[] SKU {
        get {
            return this.sKUField;
        }
        set {
            this.sKUField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/ERPInterface.xsd")]
public partial class TUCreateSKUType {
    
    private int eRPIDField;
    
    private TUCreateSKUTypeTU tuField;
    
    /// <remarks/>
    public int ERPID {
        get {
            return this.eRPIDField;
        }
        set {
            this.eRPIDField = value;
        }
    }
    
    /// <remarks/>
    public TUCreateSKUTypeTU TU {
        get {
            return this.tuField;
        }
        set {
            this.tuField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/ERPInterface.xsd")]
public partial class TUDeleteType {
    
    private int eRPIDField;
    
    private TUType[] tuField;
    
    /// <remarks/>
    public int ERPID {
        get {
            return this.eRPIDField;
        }
        set {
            this.eRPIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TU")]
    public TUType[] TU {
        get {
            return this.tuField;
        }
        set {
            this.tuField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/ERPInterface.xsd")]
public partial class TUType {
    
    private int tUIDField;
    
    private string locationField;
    
    private bool blockedField;
    
    public TUType() {
        this.locationField = "";
        this.blockedField = false;
    }
    
    /// <remarks/>
    public int TUID {
        get {
            return this.tUIDField;
        }
        set {
            this.tUIDField = value;
        }
    }
    
    /// <remarks/>
    public string Location {
        get {
            return this.locationField;
        }
        set {
            this.locationField = value;
        }
    }
    
    /// <remarks/>
    public bool Blocked {
        get {
            return this.blockedField;
        }
        set {
            this.blockedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/ERPInterface.xsd")]
public partial class TUCreateType {
    
    private int eRPIDField;
    
    private TUType[] tuField;
    
    /// <remarks/>
    public int ERPID {
        get {
            return this.eRPIDField;
        }
        set {
            this.eRPIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TU")]
    public TUType[] TU {
        get {
            return this.tuField;
        }
        set {
            this.tuField = value;
        }
    }
}
