//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace i2MFCS.WMS.Core.Xml.ERPCommand
{
    // 
    // This source code was auto-generated by xsd, Version=4.6.1055.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/ERPSubmitStatus.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/ERPSubmitStatus.xsd", IsNullable = false)]
    public partial class ERPSubmitStatus
    {

        private XMLCommandStringType xmlcommandstringField;

        private CommandType[] commandsField;

        /// <remarks/>
        public XMLCommandStringType xmlcommandstring
        {
            get
            {
                return this.xmlcommandstringField;
            }
            set
            {
                this.xmlcommandstringField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Command", IsNullable = false)]
        public CommandType[] Commands
        {
            get
            {
                return this.commandsField;
            }
            set
            {
                this.commandsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/ERPSubmitStatus.xsd")]
    public partial class XMLCommandStringType
    {

        private int statusField;

        private string extraInfoField;

        /// <remarks/>
        public int Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        public string ExtraInfo
        {
            get
            {
                return this.extraInfoField;
            }
            set
            {
                this.extraInfoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/ERPSubmitStatus.xsd")]
    public partial class CommandType
    {

        private int eRPIDField;

        private int statusField;

        private string detailsField;

        private string extraInfoField;

        /// <remarks/>
        public int ERPID
        {
            get
            {
                return this.eRPIDField;
            }
            set
            {
                this.eRPIDField = value;
            }
        }

        /// <remarks/>
        public int Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        public string Details
        {
            get
            {
                return this.detailsField;
            }
            set
            {
                this.detailsField = value;
            }
        }

        /// <remarks/>
        public string ExtraInfo
        {
            get
            {
                return this.extraInfoField;
            }
            set
            {
                this.extraInfoField = value;
            }
        }
    }

}