//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
namespace i2MFCS.WMS.Core.Xml.WMSWritePickToDocument
{

    // 
    // This source code was auto-generated by xsd, Version=4.6.1055.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/WMSWritePickToDocument.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/WMSWritePickToDocument.xsd", IsNullable = false)]
    public partial class Belgeler
    {

        private BaslikType baslikField;

        private DetayType[] detaylarField;

        /// <remarks/>
        public BaslikType Baslik
        {
            get
            {
                return this.baslikField;
            }
            set
            {
                this.baslikField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Detay", IsNullable = false)]
        public DetayType[] Detaylar
        {
            get
            {
                return this.detaylarField;
            }
            set
            {
                this.detaylarField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/WMSWritePickToDocument.xsd")]
    public partial class BaslikType
    {

        private int belgeKoduField;

        private string belgeTipiField;

        /// <remarks/>
        public int BelgeKodu
        {
            get
            {
                return this.belgeKoduField;
            }
            set
            {
                this.belgeKoduField = value;
            }
        }

        /// <remarks/>
        public string BelgeTipi
        {
            get
            {
                return this.belgeTipiField;
            }
            set
            {
                this.belgeTipiField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/WMSWritePickToDocument.xsd")]
    public partial class DetayType
    {

        private int belgeKoduField;

        private string refBelgeDetayNoField;

        private string urunKodField;

        private string miktamField;

        private string birimField;

        private string netAgirlikField;

        private string agirlikBirimiField;

        private string kaynakBatchNoField;

        private string hedefBatchNoField;

        private string seriNoField;

        private string kaynakLokasyonField;

        private string hedefStatuField;

        private int paletNoField;

        private string poField;

        private string poLineField;

        private string sKTField;

        private string uRTField;

        /// <remarks/>
        public int BelgeKodu
        {
            get
            {
                return this.belgeKoduField;
            }
            set
            {
                this.belgeKoduField = value;
            }
        }

        /// <remarks/>
        public string RefBelgeDetayNo
        {
            get
            {
                return this.refBelgeDetayNoField;
            }
            set
            {
                this.refBelgeDetayNoField = value;
            }
        }

        /// <remarks/>
        public string UrunKod
        {
            get
            {
                return this.urunKodField;
            }
            set
            {
                this.urunKodField = value;
            }
        }

        /// <remarks/>
        public string Miktam
        {
            get
            {
                return this.miktamField;
            }
            set
            {
                this.miktamField = value;
            }
        }

        /// <remarks/>
        public string Birim
        {
            get
            {
                return this.birimField;
            }
            set
            {
                this.birimField = value;
            }
        }

        /// <remarks/>
        public string NetAgirlik
        {
            get
            {
                return this.netAgirlikField;
            }
            set
            {
                this.netAgirlikField = value;
            }
        }

        /// <remarks/>
        public string AgirlikBirimi
        {
            get
            {
                return this.agirlikBirimiField;
            }
            set
            {
                this.agirlikBirimiField = value;
            }
        }

        /// <remarks/>
        public string KaynakBatchNo
        {
            get
            {
                return this.kaynakBatchNoField;
            }
            set
            {
                this.kaynakBatchNoField = value;
            }
        }

        /// <remarks/>
        public string HedefBatchNo
        {
            get
            {
                return this.hedefBatchNoField;
            }
            set
            {
                this.hedefBatchNoField = value;
            }
        }

        /// <remarks/>
        public string SeriNo
        {
            get
            {
                return this.seriNoField;
            }
            set
            {
                this.seriNoField = value;
            }
        }

        /// <remarks/>
        public string KaynakLokasyon
        {
            get
            {
                return this.kaynakLokasyonField;
            }
            set
            {
                this.kaynakLokasyonField = value;
            }
        }

        /// <remarks/>
        public string HedefStatu
        {
            get
            {
                return this.hedefStatuField;
            }
            set
            {
                this.hedefStatuField = value;
            }
        }

        /// <remarks/>
        public int PaletNo
        {
            get
            {
                return this.paletNoField;
            }
            set
            {
                this.paletNoField = value;
            }
        }

        /// <remarks/>
        public string Po
        {
            get
            {
                return this.poField;
            }
            set
            {
                this.poField = value;
            }
        }

        /// <remarks/>
        public string PoLine
        {
            get
            {
                return this.poLineField;
            }
            set
            {
                this.poLineField = value;
            }
        }

        /// <remarks/>
        public string SKT
        {
            get
            {
                return this.sKTField;
            }
            set
            {
                this.sKTField = value;
            }
        }

        /// <remarks/>
        public string URT
        {
            get
            {
                return this.uRTField;
            }
            set
            {
                this.uRTField = value;
            }
        }
    }
}