//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/WriteResultToSB.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/WriteResultToSB.xsd", IsNullable=false)]
public partial class Results {
    
    private DetailType detailField;
    
    /// <remarks/>
    public DetailType Detail {
        get {
            return this.detailField;
        }
        set {
            this.detailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/WriteResultToSB.xsd")]
public partial class DetailType {
    
    private int erpIdField;
    
    private int statusField;
    
    private string resultStringField;
    
    private string sKUIDField;
    
    private string batchField;
    
    private double quantityField;
    
    /// <remarks/>
    public int ErpId {
        get {
            return this.erpIdField;
        }
        set {
            this.erpIdField = value;
        }
    }
    
    /// <remarks/>
    public int Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    public string ResultString {
        get {
            return this.resultStringField;
        }
        set {
            this.resultStringField = value;
        }
    }
    
    /// <remarks/>
    public string SKUID {
        get {
            return this.sKUIDField;
        }
        set {
            this.sKUIDField = value;
        }
    }
    
    /// <remarks/>
    public string Batch {
        get {
            return this.batchField;
        }
        set {
            this.batchField = value;
        }
    }
    
    /// <remarks/>
    public double Quantity {
        get {
            return this.quantityField;
        }
        set {
            this.quantityField = value;
        }
    }
}
