//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
namespace i2MFCS.WMS.Core.Xml.WMSWriteMovementToSBWithBarcode
{


    // 
    // This source code was auto-generated by xsd, Version=4.6.1055.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/WMSWriteMovementToSBWithBarcode.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/WMSWriteMovementToSBWithBarcode.xsd", IsNullable = false)]
    public partial class Belgeler
    {

        private BaslikType baslikField;

        private DetayType[] detaylarField;

        private BaslikEkSahaType[] baslikEkSahalarField;

        private DetayEkSahaType[] detayEkSahalarField;

        /// <remarks/>
        public BaslikType Baslik
        {
            get
            {
                return this.baslikField;
            }
            set
            {
                this.baslikField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Detay", IsNullable = false)]
        public DetayType[] Detaylar
        {
            get
            {
                return this.detaylarField;
            }
            set
            {
                this.detaylarField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("BaslikEkSaha", IsNullable = false)]
        public BaslikEkSahaType[] BaslikEkSahalar
        {
            get
            {
                return this.baslikEkSahalarField;
            }
            set
            {
                this.baslikEkSahalarField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("DetayEkSaha", IsNullable = false)]
        public DetayEkSahaType[] DetayEkSahalar
        {
            get
            {
                return this.detayEkSahalarField;
            }
            set
            {
                this.detayEkSahalarField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/WMSWriteMovementToSBWithBarcode.xsd")]
    public partial class BaslikType
    {

        private int belgeKoduField;

        private string belgeTipiField;

        private string tesisField;

        private System.DateTime tarihField;

        private string musteriKoduField;

        private string referansNoField;

        private string aciklamaField;

        private string parcaliIslemField;

        /// <remarks/>
        public int BelgeKodu
        {
            get
            {
                return this.belgeKoduField;
            }
            set
            {
                this.belgeKoduField = value;
            }
        }

        /// <remarks/>
        public string BelgeTipi
        {
            get
            {
                return this.belgeTipiField;
            }
            set
            {
                this.belgeTipiField = value;
            }
        }

        /// <remarks/>
        public string Tesis
        {
            get
            {
                return this.tesisField;
            }
            set
            {
                this.tesisField = value;
            }
        }

        /// <remarks/>
        public System.DateTime Tarih
        {
            get
            {
                return this.tarihField;
            }
            set
            {
                this.tarihField = value;
            }
        }

        /// <remarks/>
        public string MusteriKodu
        {
            get
            {
                return this.musteriKoduField;
            }
            set
            {
                this.musteriKoduField = value;
            }
        }

        /// <remarks/>
        public string ReferansNo
        {
            get
            {
                return this.referansNoField;
            }
            set
            {
                this.referansNoField = value;
            }
        }

        /// <remarks/>
        public string Aciklama
        {
            get
            {
                return this.aciklamaField;
            }
            set
            {
                this.aciklamaField = value;
            }
        }

        /// <remarks/>
        public string ParcaliIslem
        {
            get
            {
                return this.parcaliIslemField;
            }
            set
            {
                this.parcaliIslemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/WMSWriteMovementToSBWithBarcode.xsd")]
    public partial class DetayEkSahaType
    {

        private string belgeKoduField;

        private string detayNoField;

        private string sahaKoduField;

        private string sahaDegeriField;

        /// <remarks/>
        public string BelgeKodu
        {
            get
            {
                return this.belgeKoduField;
            }
            set
            {
                this.belgeKoduField = value;
            }
        }

        /// <remarks/>
        public string DetayNo
        {
            get
            {
                return this.detayNoField;
            }
            set
            {
                this.detayNoField = value;
            }
        }

        /// <remarks/>
        public string SahaKodu
        {
            get
            {
                return this.sahaKoduField;
            }
            set
            {
                this.sahaKoduField = value;
            }
        }

        /// <remarks/>
        public string SahaDegeri
        {
            get
            {
                return this.sahaDegeriField;
            }
            set
            {
                this.sahaDegeriField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/WMSWriteMovementToSBWithBarcode.xsd")]
    public partial class BaslikEkSahaType
    {

        private string belgeKoduField;

        private string sahaKoduField;

        private string sahaDegeriField;

        /// <remarks/>
        public string BelgeKodu
        {
            get
            {
                return this.belgeKoduField;
            }
            set
            {
                this.belgeKoduField = value;
            }
        }

        /// <remarks/>
        public string SahaKodu
        {
            get
            {
                return this.sahaKoduField;
            }
            set
            {
                this.sahaKoduField = value;
            }
        }

        /// <remarks/>
        public string SahaDegeri
        {
            get
            {
                return this.sahaDegeriField;
            }
            set
            {
                this.sahaDegeriField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/WMSWriteMovementToSBWithBarcode.xsd")]
    public partial class DetayType
    {

        private string belgeKoduField;

        private string detayNoField;

        private int barkodField;

        /// <remarks/>
        public string BelgeKodu
        {
            get
            {
                return this.belgeKoduField;
            }
            set
            {
                this.belgeKoduField = value;
            }
        }

        /// <remarks/>
        public string DetayNo
        {
            get
            {
                return this.detayNoField;
            }
            set
            {
                this.detayNoField = value;
            }
        }

        /// <remarks/>
        public int Barkod
        {
            get
            {
                return this.barkodField;
            }
            set
            {
                this.barkodField = value;
            }
        }
    }
}